# Website settings
url: "https://hellenferrari.github.io/"

# Internal nav
nav:
  main:
    writing: "/writing"
    projects: "/projects"
  writing:
    all: "/writing"
    popular: "/writing/popular"
    tags: "/writing/tags"
    rss: "/feed.xml"

# Bio settings
name: "Hellen Ferrari"
description: "The home page of Hellen Ferrari, mobile developer"
thumbnail_path: ""
website_repo_url: "https://github.com/hellenferrari/hellenferrari.github.io"

# URLs
contact_urls:
  twitter:
    url: "https://twitter.com/hellenferrari"
    label: "Twitter"
    icon: "twitter-square"
    username: "@hellenferrari"
  linkedin:
    url: "https://www.linkedin.com/in/hellencferrari"
    label: "LinkedIn"
    icon: "linkedin-square"
  facebook:
    url: "https://www.facebook.com/hellencferrari"
    label: "Facebook"
    icon: "facebook-square"
  github:
    url: "https://github.com/hellenferrari/"
    label: "GitHub"
    icon: "github-square"
  email:
    url: "mailto:hellenc.ferrari@gmail.com"
    label: "Email"
    value: "hellenc.ferrari@gmail.com"
    icon: "envelope-square"

# Jekyll build settings
paginate: 10
paginate_path: "/writing/page:num"
permalink: "/writing/:year/:month/:day/:title/"
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: rouge
timezone: 'America/Vancouver'
repository: hellenferrari/hellenferrari.github.io

# Plugins (GitHub Pages only support a few)
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate

theme: minima
